# Universal group – applies to everything
[all:children]
webservers

[webservers]
web-1 ansible_host=YOUR_EC2_PUBLIC_IP
web-2 ansible_host=YOUR_EC2_PUBLIC_IP

[webservers:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/path/to/your/key.pem

# For Next 
# [databases]
# db-1 ansible_host=zz.zz.zz.zz ...

