---
- name: Install apache2
  ansible.builtin.apt:
    name: apache2
    state: present
    update_cache: true

- name: Copy custom index.html
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: "0644"
  notify: Restart apache

- name: Ensure Apache is running and enabled
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true
