# Universal group – applies to everything
[all:children]
webservers

[webservers]
#web-1 ansible_host=52.22.145.63
web-2 ansible_host=18.211.74.179

[webservers:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/mousa/dir/keys/alpha.pem
