---
- name: Compile transport map
  ansible.builtin.command: postmap /etc/postfix/transport
  changed_when: false
  notify: restart postfix

- name: Compile transport map
  ansible.builtin.command: postmap /etc/postfix/transport
  changed_when: false
  notify: restart postfix
