---
- name: Apply common system updates
  hosts: all
  become: true
  roles:
    - common

- name: Configure web servers
  hosts: webservers
  become: true
  roles:
    - java
    # pick the webserver you want apache vs nginx
    # - apache
    - nginx

- name: Apply security hardening
  hosts: all
  become: true
  roles:
    - hardening

- name: Set up system mail
  hosts: all
  become: true
  roles:
    - mail

- name: Set up Let's Encrypt
  hosts: all
  become: true
  roles:
    - letsencrypt
